######################################################################
# Automatically generated by qmake (3.0) Fri Jan 15 10:06:15 2016
######################################################################

TEMPLATE = app
TARGET = gyp-to-pri
INCLUDEPATH += .

# Input
SOURCES += main.cpp
